import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.collections': 'Collections',
    'nav.exhibitions': 'Exhibitions',
    'nav.archives': 'Archives',
    'nav.analytics': 'Analytics',
    'nav.access': 'Access Portal',
    'nav.logo_algerian': 'ALGERIAN',
    'nav.logo_heritage': 'HERITAGE',
    'nav.tagline': 'Your digital window to Algeria\'s hidden treasures',
    'hero.portal_tagline': 'Your digital window to Algeria\'s hidden treasures',
    'hero.title': 'Discover the Heart of',
    'hero.subtitle': 'Algerian Heritage',
    'hero.description': 'Explore the rich history and cultural treasures of Algeria through our national museum network.',
    'hero.search': 'Search museums, artifacts, or regions...',
    'hero.all_records': 'All Records',
    'hero.archaeology': 'Archaeology',
    'hero.arts': 'Arts',
    'hero.history': 'History',
    'hero.ethnography': 'Ethnography',
    'hero.natural_history': 'Natural History',
    'hero.search_btn': 'Search',
    'hero.cta': 'Explore Registry',
    'hero.institutions': 'Institutions',
    'hero.archived': 'Archived Records',
    'hero.years': 'Years of History',
    'hero.monument': 'National Monument',
    'hero.algiers': 'Algiers, Algeria',
    'hero.tagline': 'Preserving the Soul of a Nation',
    'mission.title': 'بصمة المشروع: Our Legacy',
    'mission.arabic_title': 'بصمة المشروع',
    'mission.tagline': 'Our Sacred Mission',
    'mission.description': 'We believe that heritage is not just a past to be preserved, but a identity to be built and roots that extend from the depth of the present into the future.\n\nFrom this belief, our project was born to be a bridge linking heritage and technology, giving our cultural legacy a new life in the digital world.\n\nWe work on collecting, documenting, and presenting Algerian cultural heritage using modern digital tools, ensuring its accessibility to everyone in an accurate, reliable, and interactive manner.\n\nWe are committed to preserving the authenticity of content, respecting its historical and cultural values, relying on reliable sources, and providing accurate information free from distortion or falsification.\n\nWe believe that digitization is not just a means of display, but a civilizational responsibility that contributes to protecting heritage from extinction and delivering it to future generations in a way that keeps pace with their era.\n\nWe are not just building a digital platform, but establishing an entity that carries a message: heritage is not forgotten... but preserved, lived, and told again.',
    'mission.preservation': 'Preservation',
    'mission.accessibility': 'Accessibility',
    'mission.archives': 'State-of-the-art Archives',
    'mission.digital': 'Global Digital Access',
    'mission.charter': 'Read Our Full Charter',
    'mission.education': 'Education',
    'mission.education_desc': 'Empowering the next generation with historical truth.',
    'mission.research': 'Research',
    'mission.research_desc': 'Providing a global platform for archaeological study.',
    'mission.unesco': 'UNESCO Partner',
    'mission.soul': 'Preserving the Soul of Algeria',
    'mission.soul_desc': 'Our mission transcends simple archiving. We are the custodians of a 3,000-year-old narrative, ensuring that the echoes of our ancestors resonate through the digital age.',
    'spotlight.title': 'The Spirit of Resistance',
    'spotlight.arabic_title': 'روح المقاومة والتحرر',
    'spotlight.tagline': 'National Spotlight',
    'spotlight.description': 'A journey through the corridors of time, where every artifact tells a story of bravery, sacrifice, and the unyielding pursuit of freedom.',
    'spotlight.cta': 'Explore the Revolution',
    'spotlight.featured': 'Featured Site',
    'spotlight.maqam': 'Maqam Echahid',
    'spotlight.verified': 'Verified Archive',
    'spotlight.mujahid_desc': 'The National Museum of Mujahid preserves over 50,000 artifacts from the Algerian War of Independence.',
    'spotlight.year': '1962',
    'treasury.title': 'The National Treasury',
    'treasury.arabic_title': 'الخزانة الوطنية للتراث الجزائري',
    'treasury.tagline': 'Curated Masterpieces',
    'treasury.description': 'A meticulous selection of Algeria\'s most significant artifacts, spanning from the prehistoric era to the modern age of independence.',
    'treasury.examine': 'Examine Archive Record',
    'treasury.registry_count': 'Registry Count',
    'treasury.last_updated': 'Last Updated',
    'treasury.month': 'MAR 2026',
    'inventory.title': 'National Museum Directory',
    'inventory.arabic_title': 'الدليل الوطني للمتاحف الجزائرية',
    'inventory.tagline': 'Institutional Registry',
    'inventory.active': 'Active Registry Records',
    'inventory.no_results': 'No Institutions Found',
    'inventory.reset': 'Reset Directory Filters',
    'inventory.active_records': 'Verified Institutions',
    'inventory.no_matching': 'Registry Conflict',
    'inventory.no_matching_desc': 'The national registry could not locate any institutions matching your search query in the current database.',
    'filters.wilaya': 'Wilaya',
    'filters.category': 'Category',
    'filters.era': 'Historical Era',
    'filters.all': 'All',
    'nav.favorites': 'Saved',
    'ai.title': 'Heritage AI Guide',
    'ai.tagline': 'Digital Assistant',
    'ai.placeholder': 'Ask me about Algerian history...',
    'ai.disclaimer': 'AI guide powered by national archives.',
    'ai.close': 'Close Assistant',
    'ai.open': 'Open Heritage Guide',
    'ai.error': 'Connection lost with archives.',
    'ai.welcome': 'Welcome. I am your digital guide to Algeria\'s hidden treasures. How can I assist your discovery today?',
    'favorites.title': 'Saved Institutions',
    'favorites.empty': 'You haven\'t saved any institutions yet.',
    'atlas.title': 'The Heritage Atlas',
    'atlas.arabic_title': 'أطلس التراث الوطني',
    'atlas.tagline': 'Geographic Discovery',
    'atlas.cta': 'Open Interactive Atlas',
    'eras.chronicles': 'Chronicles of Time',
    'eras.title': 'The Eras of Civilization',
    'eras.view_archives': 'View Archives',
    'eras.verified': 'Verified Era',
    'eras.period': 'Historical Period',
    'museum.access_coords': 'Access Coordinates',
    'museum.gps': 'GPS',
    'museum.algeria': 'Algeria',
    'museum.region': 'Region',
    'museum.archive_preview': 'Digital Archive Preview',
    'museum.scan_count': 'SCAN_COUNT',
    'museum.status_open': 'Status: Open',
    'museum.access_fee': 'Access Fee',
    'museum.fee_adult': 'Adult',
    'museum.fee_student': 'Student',
    'museum.fee_currency': 'DZD',
    'museum.photography': 'Photography',
    'museum.photo_allowed': 'Permitted',
    'museum.photo_not_allowed': 'Not Permitted',
    'museum.contact_info': 'Contact Information',
    'museum.phone': 'Phone',
    'museum.verified_archive': 'Ministry Verified Archive',
    'museum.certified': 'Ministry Certified Institution',
    'museum.view_entry': 'View Registry Record',
    'museum.back': 'Back to Directory',
    'museum.archive_summary': 'Institutional Archive Summary',
    'museum.digital_collection': 'Digital Archive Collection',
    'museum.photos': 'Museum Photos',
    'artifact.era': 'Chronological Era',
    'artifact.registry_entry': 'Registry Entry',
    'artifact.custodian': 'Current Custodian',
    'artifact.verification': 'Verification Status',
    'artifact.authentic': 'Authentic — National Registry Verified',
    'dashboard.census': 'National Heritage Census 2026',
    'dashboard.performance': 'Institutional Performance',
    'dashboard.report': 'National Heritage Institutional Performance Report',
    'dashboard.integrity': 'Data Integrity Verified',
    'dashboard.ministry': 'Ministry of Culture & Arts',
    'dashboard.reg_inst': 'Registered Institutions',
    'dashboard.visitors': 'Verified Annual Visitors',
    'dashboard.satisfaction': 'Public Satisfaction Index',
    'dashboard.wilayas': 'Administrative Wilayas',
    'dashboard.matrix': 'Visitor Distribution Matrix',
    'dashboard.traffic': 'Monthly Institutional Traffic',
    'dashboard.distribution': 'Visitor Distribution',
    'dashboard.metrics': 'Monthly Traffic Metrics',
    'dashboard.density': 'Regional Density',
    'dashboard.geo_dist': 'Geographic Distribution',
    'dashboard.heritage_density': 'Heritage Density',
    'dashboard.sector': 'Sector',
    'dashboard.units': 'Units',
    'dashboard.geospatial': 'Access Digital Heritage Atlas',
    'chronicles.title': 'The Heritage Chronicles',
    'chronicles.arabic_title': 'سجلات التراث الخالدة عبر العصور',
    'chronicles.tagline': 'Historical Timeline',
    'footer.tagline': 'An independent digital initiative dedicated to celebrating and documenting Algerian cultural and historical heritage for educational purposes.',
    'footer.registry': 'Directory',
    'footer.archives': 'Gallery',
    'footer.about': 'About',
    'footer.disclaimer_text': 'This platform is an independent digital initiative aimed at promoting Algerian cultural and historical heritage. It is not affiliated with any official government institution or museum management.',
    'footer.copyright': '© 2026 Independent Algerian Cultural Initiative',
    'footer.privacy': 'Privacy & Legal',
    'footer.terms': 'Usage Terms',
    'footer.independent_note': 'Independent Cultural Initiative',
    'legal.title': 'Terms of Use & Legal Policy',
    'legal.intro': 'Welcome to "MuseumDZ", an independent digital initiative. By using this platform, you agree to the following terms:',
    'legal.item1_title': '1. Independence',
    'legal.item1_desc': 'This platform is a private cultural initiative and does not represent any official government or institutional body. Information is provided for educational and documentation purposes only.',
    'legal.item2_title': '2. Intellectual Property',
    'legal.item2_desc': 'All visual content and archival data are protected. Commercial use of the platform\'s assets without prior written consent is strictly prohibited.',
    'legal.item3_title': '3. Information Accuracy',
    'legal.item3_desc': 'While we strive for precision, we do not guarantee real-time updates for museum hours or ticket prices. Users are encouraged to verify with the physical institutions directly.',
    'legal.item4_title': '4. Data Privacy',
    'legal.item4_desc': 'We respect your privacy. This platform does not collect, store, or sell personal visitor data. Your browsing experience is completely private.',
    'legal.item5_title': '5. Limitation of Liability',
    'legal.item5_desc': 'The initiative is not liable for any historical interpretations or external links provided. Our role is solely the digital preservation of heritage awareness.',
    'legal.close': 'Close Policy',
  },
  ar: {
    'nav.collections': 'المجموعات',
    'nav.exhibitions': 'المعارض',
    'nav.archives': 'الأرشيف',
    'nav.analytics': 'التحليلات',
    'nav.access': 'بوابة الدخول',
    'nav.logo_algerian': 'التراث',
    'nav.logo_heritage': 'الجزائري',
    'nav.tagline': 'نافذتك الرقمية على كنوز الجزائر المخفية',
    'hero.portal_tagline': 'نافذتك الرقمية على كنوز الجزائر المخفية',
    'hero.title': 'اكتشف قلب',
    'hero.subtitle': 'التراث الجزائري',
    'hero.description': 'استكشف التاريخ الغني والكنوز الثقافية للجزائر من خلال شبكة متاحفنا الوطنية.',
    'hero.search': 'ابحث عن المتاحف، الآثار، أو المناطق...',
    'hero.all_records': 'كل السجلات',
    'hero.archaeology': 'علم الآثار',
    'hero.arts': 'الفنون',
    'hero.history': 'التاريخ',
    'hero.ethnography': 'الإثنوغرافيا',
    'hero.natural_history': 'التاريخ الطبيعي',
    'hero.search_btn': 'بحث',
    'hero.cta': 'استكشف السجل',
    'hero.institutions': 'مؤسسة',
    'hero.archived': 'سجل مؤرشف',
    'hero.years': 'سنة من التاريخ',
    'hero.monument': 'معلم وطني',
    'hero.algiers': 'الجزائر العاصمة',
    'hero.tagline': 'حماية روح الأمة',
    'mission.title': 'بصمة المشروع: هويتنا وأهدافنا',
    'mission.arabic_title': 'بصمة المشروع',
    'mission.tagline': 'مهمتنا المقدسة',
    'mission.description': 'نؤمن بأن التراث ليس مجرد ماضٍ يُحفظ، بل هو هويةٌ تُبنى وجذورٌ تمتد في عمق الحاضر نحو المستقبل.\n\nومن هذا الإيمان، وُولد مشروعنا ليكون جسراً يربط بين التراث والتكنولوجيا، ويمنح موروثنا الثقافي حياةً جديدة في العالم الرقمي.\n\nنعمل على جمع وتوثيق وعرض التراث الثقافي الجزائري باستخدام أدوات رقمية حديثة، تضمن إتاحته للجميع بأسلوب دقيق، موثوق، وتفاعلي.\n\nنلتزم بالحفاظ على أصالة المحتوى، واحترام قيمه التاريخية والثقافية، مع الاعتماد على مصادر موثوقة، وتقديم معلومات دقيقة خالية من التشويه أو التزييف.\n\nنؤمن بأن الرقمنة ليست مجرد وسيلة عرض، بل مسؤولية حضارية تُسهم في حماية التراث من الاندثار، وإيصاله إلى الأجيال القادمة بطريقة تواكب عصرهم.\n\nنحن لا نبني مجرد منصة رقمية، بل نؤسس كيانًا يحمل رسالة:\nأن التراث لا يُنسى… بل يُصان، ويُحيا، ويُروى من جديد.',
    'mission.preservation': 'الحفاظ',
    'mission.accessibility': 'الوصول',
    'mission.archives': 'أرشيفات متطورة',
    'mission.digital': 'وصول رقمي عالمي',
    'mission.charter': 'اقرأ ميثاقنا الكامل',
    'mission.education': 'التعليم',
    'mission.education_desc': 'تمكين الجيل القادم من الحقيقة التاريخية.',
    'mission.research': 'البحث',
    'mission.research_desc': 'توفير منصة عالمية للدراسات الأثرية.',
    'mission.unesco': 'شريك اليونسكو',
    'mission.soul': 'الحفاظ على روح الجزائر',
    'mission.soul_desc': 'مهمتنا تتجاوز مجرد الأرشفة. نحن حراس رواية عمرها 3000 عام، نضمن أن أصداء أسلافنا تتردد عبر العصر الرقمي.',
    'spotlight.title': 'روح المقاومة والتحرر',
    'spotlight.tagline': 'تسليط الضوء',
    'spotlight.description': 'رحلة عبر أروقة الزمن، حيث تحكي كل قطعة أثرية قصة شجاعة وتضحية وسعي لا يلين نحو الحرية.',
    'spotlight.cta': 'استكشف التاريخ',
    'spotlight.featured': 'موقع مميز',
    'spotlight.maqam': 'مقام الشهيد',
    'spotlight.verified': 'توثيق رقمي',
    'spotlight.mujahid_desc': 'يضم المتحف الوطني للمجاهد آلاف القطع الأثرية التي توثق ثورة التحرير الجزائرية العظيمة.',
    'spotlight.year': '1962',
    'treasury.title': 'كنوز الجزائر',
    'treasury.arabic_title': 'من روائع التراث الجزائري',
    'treasury.tagline': 'روائع مختارة',
    'treasury.description': 'مجموعة من أهم الآثار الجزائرية، تمتد من عصور ما قبل التاريخ إلى العصر الحديث.',
    'treasury.examine': 'فحص السجل الرقمي',
    'treasury.registry_count': 'عدد المدخلات',
    'treasury.last_updated': 'آخر تحديث',
    'treasury.month': 'مارس 2026',
    'inventory.title': 'دليل المتاحف',
    'inventory.arabic_title': 'دليل المتاحف الجزائرية',
    'inventory.tagline': 'دليل ثقافي',
    'inventory.active': 'سجلات المتاحف النشطة',
    'inventory.no_results': 'لم يتم العثور على متاحف',
    'inventory.reset': 'إعادة ضبط مرشحات الدليل',
    'inventory.active_records': 'المتاحف المدرجة',
    'inventory.no_matching': 'تعذر العثور على سجل',
    'inventory.no_matching_desc': 'لم يتم العثور على متاحف تطابق استعلام البحث الخاص بك في قاعدة البيانات الحالية.',
    'filters.wilaya': 'الولاية',
    'filters.category': 'نوع المتحف',
    'filters.era': 'الحقبة الزمنية',
    'filters.all': 'الكل',
    'nav.favorites': 'المحفوظات',
    'ai.title': 'دليل التراث الذكي',
    'ai.tagline': 'المساعد الرقمي',
    'ai.placeholder': 'اسألني عن تاريخ الجزائر...',
    'ai.disclaimer': 'دليل ذكاء اصطناعي مستقل يعتمد على التوثيق الرقمي.',
    'ai.close': 'إغلاق المساعد',
    'ai.open': 'فتح دليل التراث',
    'ai.error': 'فقد الاتصال مع المساعد.',
    'ai.welcome': 'مرحباً بك. أنا دليلك الرقمي المستقل لكنوز الجزائر المخفية. كيف يمكنني مساعدتك في رحلة اكتشافك اليوم؟',
    'favorites.title': 'المجموعات المحفوظة',
    'favorites.empty': 'لم تقم بحفظ أي متاحف بعد.',
    'atlas.title': 'أطلس التراث',
    'atlas.arabic_title': 'أطلس التراث الجزائري',
    'atlas.tagline': 'الاكتشاف الجغرافي',
    'atlas.cta': 'افتح الأطلس التفاعلي',
    'eras.chronicles': 'سجلات الزمن',
    'eras.title': 'عصور الحضارة',
    'eras.view_archives': 'عرض المعرض',
    'eras.verified': 'عصر تاريخي',
    'eras.period': 'الفترة التاريخية',
    'museum.access_coords': 'الوصول إلى الإحداثيات',
    'museum.gps': 'نظام تحديد المواقع',
    'museum.algeria': 'الجزائر',
    'museum.region': 'المنطقة',
    'museum.archive_preview': 'معاينة المعرض الرقمي',
    'museum.scan_count': 'عدد المسحات',
    'museum.status_open': 'الحالة: مفتوح',
    'museum.access_fee': 'رسوم الدخول',
    'museum.fee_adult': 'للكبار',
    'museum.fee_student': 'للطلبة',
    'museum.fee_currency': 'دج',
    'museum.photography': 'التصوير',
    'museum.photo_allowed': 'مسموح',
    'museum.photo_not_allowed': 'غير مسموح',
    'museum.contact_info': 'معلومات إضافية',
    'museum.phone': 'الموقع',
    'museum.verified_archive': 'توثيق رقمي مستقل',
    'museum.certified': 'مبادرة ثقافية مستقلة',
    'museum.view_entry': 'عرض سجل المتحف',
    'museum.back': 'الرجوع للقائمة',
    'museum.archive_summary': 'ملخص الدليل الرقمي',
    'museum.digital_collection': 'مجموعة المعرض الرقمي',
    'museum.photos': 'صور المتحف',
    'artifact.era': 'العصر الزمني',
    'artifact.registry_entry': 'إدخال الدليل',
    'artifact.custodian': 'المكان الحالي',
    'artifact.verification': 'حالة التوثيق',
    'artifact.authentic': 'أصيل — موثق رقمياً',
    'dashboard.census': 'الإحصاء الثقافي 2026',
    'dashboard.performance': 'الاهتمام العام بالصروح الثقافية',
    'dashboard.report': 'تقرير الاهتمام بالمعالم التراثية الوطنية',
    'dashboard.integrity': 'تم التحقق من دقة البيانات',
    'dashboard.ministry': 'مبادرة ثقافية مستقلة',
    'dashboard.reg_inst': 'المتاحف المدرجة',
    'dashboard.visitors': 'زوار سنويون (تقديري)',
    'dashboard.satisfaction': 'مؤشر الاهتمام العام',
    'dashboard.wilayas': 'الولايات',
    'dashboard.matrix': 'مصفوفة اهتمام الزوار',
    'dashboard.traffic': 'معدل الاهتمام الشهري',
    'dashboard.distribution': 'توزيع الاهتمام',
    'dashboard.metrics': 'مقاييس التفاعل الشهري',
    'dashboard.density': 'التوزع الإقليمي',
    'dashboard.geo_dist': 'التوزيع الجغرافي',
    'dashboard.heritage_density': 'كثافة المواقع',
    'dashboard.sector': 'قطاع',
    'dashboard.units': 'وحدات',
    'dashboard.geospatial': 'الوصول إلى الأطلس الجغرافي الرقمي',
    'chronicles.title': 'سجلات التراث',
    'chronicles.arabic_title': 'سجلات التراث الخالدة عبر العصور',
    'chronicles.tagline': 'الخط الزمني التاريخي',
    'footer.tagline': 'منصة رقمية مستقلة تهدف إلى التعريف بالتراث الثقافي والتاريخي للجزائر والحفاظ على الذاكرة الوطنية لأغراض تثقيفية.',
    'footer.registry': 'الدليل',
    'footer.archives': 'المجموعات',
    'footer.about': 'حول المنصة',
    'footer.disclaimer_text': 'هذه المنصة هي مبادرة رقمية مستقلة تهدف إلى الترويج للتراث الثقافي والتاريخي الجزائري. لا تتبع لأي مؤسسة حكومية رسمية أو إدارة متاحف.',
    'footer.copyright': '© 2026 - مبادرة ثقافية جزائرية مستقلة',
    'footer.privacy': 'الخصوصية والقانون',
    'footer.terms': 'شروط الاستخدام',
    'footer.independent_note': 'مبادرة ثقافية مستقلة',
    'legal.title': 'شروط الاستخدام والسياسة القانونية',
    'legal.intro': 'مرحبًا بك في منصة "MuseumDZ"، وهي مبادرة رقمية مستقلة. باستخدامك لهذه المنصة، فإنك توافق على الشروط والقوانين التالية:',
    'legal.item1_title': '1. استقلالية المنصة',
    'legal.item1_desc': 'هذه المنصة هي مبادرة ثقافية خاصة لا تمثل أي جهة حكومية أو مؤسسة رسمية؛ المعلومات المقدمة هي لأغراض تثقيفية وتوثيقية بحتة تحت مسؤولية القائمين عليها كمبادرة فكرية.',
    'legal.item2_title': '2. الملكية الفكرية',
    'legal.item2_desc': 'جميع المحتويات البصرية والبيانات الأرشيفية المعروضة محمية بحقوق النشر. يمنع منعاً باتاً استخدام أي من أصول المنصة لأغراض تجارية دون الحصول على إذن كتابي مسبق.',
    'legal.item3_title': '3. دقة البيانات',
    'legal.item3_desc': 'رغم حرصنا على الدقة، لا نضمن التحديث اللحظي لبيانات المؤسسات (مثل مواعيد العمل أو الأسعار). ننصح الزوار بالتأكد من المعلومات من مقرات المتاحف مباشرة قبل الزيارة.',
    'legal.item4_title': '4. خصوصية البيانات',
    'legal.item4_desc': 'نحن نحترم خصوصيتك تماماً. لا تقوم هذه المنصة بجمع أو تخزين أو بيع أي بيانات شخصية للزوار. تجربة التصفح الخاصة بك آمنة وخاصة بالكامل.',
    'legal.item5_title': '5. حدود المسؤولية',
    'legal.item5_desc': 'لا تتحمل المبادرة أي مسؤولية عن التفسيرات التاريخية أو المحتوى الخارجي. دورنا ينحصر في تعزيز الوعي بالتراث الوطني عبر الأرشفة الرقمية فقط.',
    'legal.close': 'إغلاق السياسة',
  },
  fr: {
    'nav.collections': 'Collections',
    'nav.exhibitions': 'Expositions',
    'nav.archives': 'Archives',
    'nav.analytics': 'Analyses',
    'nav.access': 'Portail d\'Accès',
    'nav.logo_algerian': 'PATRIMOINE',
    'nav.logo_heritage': 'ALGÉRIEN',
    'nav.tagline': 'Votre fenêtre numérique sur les trésors cachés de l\'Algérie',
    'hero.portal_tagline': 'Votre fenêtre numérique sur les trésors cachés de l\'Algérie',
    'hero.title': 'Découvrez le Cœur du',
    'hero.subtitle': 'Patrimoine Algérien',
    'hero.description': 'Explorez la riche histoire et les trésors culturels de l\'Algérie à travers notre réseau national de musées.',
    'hero.search': 'Rechercher des musées, des artefacts ou des régions...',
    'hero.all_records': 'Tous les Dossiers',
    'hero.archaeology': 'Archéologie',
    'hero.arts': 'Arts',
    'hero.history': 'Histoire',
    'hero.ethnography': 'Ethnographie',
    'hero.natural_history': 'Histoire Naturelle',
    'hero.search_btn': 'Rechercher',
    'hero.cta': 'Explorer le Registre',
    'hero.institutions': 'Institutions',
    'hero.archived': 'Dossiers Archivés',
    'hero.years': 'Années d\'Histoire',
    'hero.monument': 'Monument National',
    'hero.algiers': 'Alger, Algérie',
    'hero.tagline': 'Préserver l\'Âme d\'une Nation',
    'mission.title': 'بصمة المشروع: Notre Héritage',
    'mission.arabic_title': 'بصمة المشروع',
    'mission.tagline': 'Notre Mission Sacrée',
    'mission.description': 'Nous croyons que le patrimoine n\'est pas seulement un passé à préserver, mais une identité à construire et des racines qui s\'étendent des profondeurs du présent vers l\'avenir.\n\nDe cette conviction est né notre projet pour être un pont liant le patrimoine et la technologie, redonnant vie à notre héritage culturel dans le monde numérique.\n\nNous travaillons sur la collecte, la documentation et la présentation du patrimoine culturel algérien en utilisant des outils numériques modernes, garantissant son accessibilité à tous de manière précise, fiable et interactive.\n\nNous nous engageons à préserver l\'authenticité du contenu, en respectant ses valeurs historiques et culturelles, tout en nous appuyant sur des sources fiables et en fournissant des informations précises sans déformatiion ni falsification.\n\nNous pensons que la numérisation n\'est pas seulement un moyen d\'affichage, mais une responsabilité civilisationnelle qui contribue à protéger le patrimoine de l\'extinction et à le transmettre aux générations futures d\'une manière qui suit le rythme de leur époque.\n\nNous ne construisons pas seulement une plateforme numérique, mais nous établissons une entité qui porte un message : le patrimoine n\'est pas oublié... mais préservé, vécu et raconté à nouveau.',
    'mission.preservation': 'Préservation',
    'mission.accessibility': 'Accessibilité',
    'mission.archives': 'Archives de Pointe',
    'mission.digital': 'Accès Numérique Mondial',
    'mission.charter': 'Lire Notre Charte Complète',
    'mission.education': 'Éducation',
    'mission.education_desc': 'Donner aux générations futures la vérité historique.',
    'mission.research': 'Recherche',
    'mission.research_desc': 'Fournir une plateforme mondiale pour l\'étude archéologique.',
    'mission.unesco': 'Partenaire de l\'UNESCO',
    'mission.soul': 'Préserver l\'Âme de l\'Algérie',
    'mission.soul_desc': 'Notre mission transcende le simple archivage. Nous sommes les gardiens d\'un récit de 3 000 ans, veillant à ce que les échos de nos ancêtres résonnent à l\'ère numérique.',
    'spotlight.title': 'L\'Esprit de Résistance',
    'spotlight.arabic_title': 'روح المقاومة والتحرر',
    'spotlight.tagline': 'Projecteur National',
    'spotlight.description': 'Un voyage à travers les couloirs du temps, où chaque artefact raconte une histoire de bravoure, de sacrifice et de poursuite inébranlable de la liberté.',
    'spotlight.cta': 'Explorer l\'Histoire',
    'spotlight.featured': 'Site Vedette',
    'artifact.verification': 'Statut de Documentation',
    'artifact.authentic': 'Authentique — Documenté Numériquement',
    'dashboard.census': 'Recensement Culturel',
    'dashboard.performance': 'Intérêt Public',
    'dashboard.report': 'Rapport d\'Intérêt pour le Patrimoine National',
    'dashboard.integrity': 'Vérification de Données Indépendante',
    'dashboard.ministry': 'Initiative Culturelle Indépendante',
    'dashboard.reg_inst': 'Musées Répertoriés',
    'dashboard.visitors': 'Visiteurs Annuels Estimés',
    'dashboard.satisfaction': 'Indice d\'Intérêt du Public',
    'dashboard.wilayas': 'Wilayas Administratives',
    'dashboard.matrix': 'Matrice de Distribution des Visiteurs',
    'dashboard.traffic': 'Trafic Mensuel Estimé',
    'dashboard.distribution': 'Distribution des Visiteurs',
    'dashboard.metrics': 'Mesures de Trafic Mensuel',
    'dashboard.density': 'Densité Régionale',
    'dashboard.geo_dist': 'Distribution Géographique',
    'dashboard.heritage_density': 'Densité du Patrimoine',
    'dashboard.sector': 'Secteur',
    'dashboard.units': 'Unités',
    'dashboard.geospatial': 'Accéder à l\'Atlas Géospatial du Patrimoine',
    'chronicles.title': 'Les Chroniques du Patrimoine',
    'chronicles.arabic_title': 'سجلات التراث الخالدة عبر العصور',
    'chronicles.tagline': 'Ligne du Temps Historique',
    'ai.welcome': 'Bienvenue. Je suis votre guide numérique indépendant des trésors cachés de l\'Algérie. Comment puis-je vous aider dans votre découverte aujourd\'hui ?',
    'favorites.title': 'Collections Enregistrées',
    'favorites.empty': 'Vous n\'avez pas encore enregistré d\'institutions.',
    'atlas.title': 'L\'Atlas du Patrimoine',
    'atlas.arabic_title': 'أطلس التراث الوطني',
    'atlas.tagline': 'Découverte Géographique',
    'atlas.cta': 'Ouvrir l\'Atlas Interactif',
    'eras.chronicles': 'Chroniques du Temps',
    'eras.title': 'Les Ères de la Civilisation',
    'eras.view_archives': 'Voir les Archives',
    'eras.verified': 'Ère Vérifiée',
    'eras.period': 'Période Historique',
    'museum.access_coords': 'Coordonnées d\'Accès',
    'museum.gps': 'GPS',
    'museum.algeria': 'Algérie',
    'museum.region': 'Région',
    'museum.archive_preview': 'Aperçu de l\'Archive Numérique',
    'museum.scan_count': 'NOMBRE_SCANS',
    'museum.status_open': 'Statut: Ouvert',
    'museum.access_fee': 'Frais d\'Accès',
    'museum.fee_adult': 'Adulte',
    'museum.fee_student': 'Étudiant',
    'museum.fee_currency': 'DA',
    'museum.photography': 'Photographie',
    'museum.photo_allowed': 'Autorisée',
    'museum.photo_not_allowed': 'Interdite',
    'museum.contact_info': 'Informations de Contact',
    'museum.phone': 'Téléphone',
    'museum.verified_archive': 'Documentation Digitale Indépendante',
    'museum.certified': 'Initiative Culturelle Indépendante',
    'museum.view_entry': 'Voir la Fiche',
    'museum.back': 'Retour au Répertoire',
    'museum.archive_summary': 'Résumé Digital',
    'museum.digital_collection': 'Collection Digitale',
    'museum.photos': 'Photos du Musée',
    'artifact.era': 'Ère Chronologique',
    'footer.tagline': 'Une initiative numérique indépendante dédiée à la célébration et à la documentation du patrimoine culturel et historique algérien à des fins éducatives.',
    'footer.registry': 'Annuaire',
    'footer.archives': 'Galerie',
    'footer.about': 'À propos',
    'footer.disclaimer_text': 'Cette plateforme est une initiative numérique indépendante visant à promouvoir le patrimoine culturel et historique algérien. Elle n\'est affiliée à aucune institution gouvernementale officielle ni gestion de musée.',
    'footer.copyright': '© 2026 Initiative Culturelle Algérienne Indépendante',
    'footer.privacy': 'Confidentialité et Mentions Légales',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.independent_note': 'Initiative Culturelle Indépendante',
    'legal.title': 'Conditions d\'Utilisation et Politique Légale',
    'legal.intro': 'Bienvenue sur "MuseumDZ", une initiative numérique indépendante. En utilisant cette plateforme, vous acceptez les conditions suivantes :',
    'legal.item1_title': '1. Indépendance',
    'legal.item1_desc': 'Cette plateforme est une initiative culturelle privée et ne représente aucun organisme gouvernemental ou institutionnel officiel. Les informations sont fournies à titre éducatif et documentaire uniquement.',
    'legal.item2_title': '2. Propriété Intellectuelle',
    'legal.item2_desc': 'Tout le contenu visuel et les données d\'archives sont protégés. L\'utilisation commerciale des actifs de la plateforme sans consentement écrit préalable est strictement interdite.',
    'legal.item3_title': '3. Exactitude des Informations',
    'legal.item3_desc': 'Bien que nous recherchions la précision, nous ne garantissons pas les mises à jour en temps réel des horaires ou des tarifs des musées. Les utilisateurs sont encouragés à vérifier directement auprès des institutions.',
    'legal.item4_title': '4. Confidentialité des Données',
    'legal.item4_desc': 'Nous respectons votre vie privée. Cette plateforme ne collecte, ne stocke ni ne vend de données personnelles sur les visiteurs. Votre expérience de navigation est totalement privée.',
    'legal.item5_title': '5. Limitation de Responsabilité',
    'legal.item5_desc': 'L\'initiative n\'est pas responsable des interprétations historiques ou des liens externes fournis. Notre rôle est uniquement la préservation numérique de la sensibilisation au patrimoine.',
    'legal.close': 'Fermer la Politique',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
