import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.collections': 'Collections',
    'nav.exhibitions': 'Exhibitions',
    'nav.archives': 'Archives',
    'nav.analytics': 'Analytics',
    'nav.access': 'Access Portal',
    'nav.logo_algerian': 'ALGERIAN',
    'nav.logo_heritage': 'HERITAGE',
    'nav.tagline': 'National Museum Portal',
    'hero.portal_tagline': 'National Heritage Portal — Algeria',
    'hero.title': 'Discover the Heart of',
    'hero.subtitle': 'Algerian Heritage',
    'hero.description': 'Explore the rich history and cultural treasures of Algeria through our national museum network.',
    'hero.search': 'Search museums, artifacts, or regions...',
    'hero.all_records': 'All Records',
    'hero.archaeology': 'Archaeology',
    'hero.fine_arts': 'Fine Arts',
    'hero.history': 'History',
    'hero.search_btn': 'Search',
    'hero.cta': 'Explore Registry',
    'hero.institutions': 'Institutions',
    'hero.archived': 'Archived Records',
    'hero.years': 'Years of History',
    'hero.monument': 'National Monument',
    'hero.algiers': 'Algiers, Algeria',
    'hero.tagline': 'Preserving the Soul of a Nation',
    'mission.title': 'Guardians of The Eternal Flame',
    'mission.arabic_title': 'حراس الشعلة الأبدية للتراث',
    'mission.tagline': 'Our Sacred Mission',
    'mission.description': 'We believe that heritage is not just a collection of objects, but a living dialogue between our ancestors and the future. Our mission is to ensure that every Algerian, wherever they may be, can touch the soul of their history.',
    'mission.preservation': 'Preservation',
    'mission.accessibility': 'Accessibility',
    'mission.archives': 'State-of-the-art Archives',
    'mission.digital': 'Global Digital Access',
    'mission.charter': 'Read Our Full Charter',
    'mission.education': 'Education',
    'mission.education_desc': 'Empowering the next generation with historical truth.',
    'mission.research': 'Research',
    'mission.research_desc': 'Providing a global platform for archaeological study.',
    'mission.unesco': 'UNESCO Partner',
    'mission.soul': 'Preserving the Soul of Algeria',
    'mission.soul_desc': 'Our mission transcends simple archiving. We are the custodians of a 3,000-year-old narrative, ensuring that the echoes of our ancestors resonate through the digital age.',
    'spotlight.title': 'The Spirit of Resistance',
    'spotlight.arabic_title': 'روح المقاومة والتحرر',
    'spotlight.tagline': 'National Spotlight',
    'spotlight.description': 'A journey through the corridors of time, where every artifact tells a story of bravery, sacrifice, and the unyielding pursuit of freedom.',
    'spotlight.cta': 'Explore the Revolution',
    'spotlight.featured': 'Featured Site',
    'spotlight.maqam': 'Maqam Echahid',
    'spotlight.verified': 'Verified Archive',
    'spotlight.mujahid_desc': 'The National Museum of Mujahid preserves over 50,000 artifacts from the Algerian War of Independence.',
    'spotlight.year': '1962',
    'treasury.title': 'The National Treasury',
    'treasury.arabic_title': 'الخزانة الوطنية للتراث الجزائري',
    'treasury.tagline': 'Curated Masterpieces',
    'treasury.description': 'A meticulous selection of Algeria\'s most significant artifacts, spanning from the prehistoric era to the modern age of independence.',
    'treasury.examine': 'Examine Archive Record',
    'treasury.registry_count': 'Registry Count',
    'treasury.last_updated': 'Last Updated',
    'treasury.month': 'MAR 2026',
    'inventory.title': 'Institutional Archives',
    'inventory.arabic_title': 'سجل المؤسسات التراثية المعتمدة',
    'inventory.tagline': 'National Registry',
    'inventory.active': 'Active Registry Records',
    'inventory.no_results': 'No Matching Records',
    'inventory.reset': 'Reset Registry Filters',
    'inventory.active_records': 'Active Registry Records',
    'inventory.no_matching': 'No Matching Records',
    'inventory.no_matching_desc': 'The registry could not find any institutions matching your current search parameters.',
    'atlas.title': 'The Heritage Atlas',
    'atlas.arabic_title': 'أطلس التراث الوطني',
    'atlas.tagline': 'Geographic Discovery',
    'atlas.cta': 'Open Interactive Atlas',
    'eras.chronicles': 'Chronicles of Time',
    'eras.title': 'The Eras of Civilization',
    'eras.view_archives': 'View Archives',
    'eras.verified': 'Verified Era',
    'eras.period': 'Historical Period',
    'museum.access_coords': 'Access Coordinates',
    'museum.gps': 'GPS',
    'museum.algeria': 'Algeria',
    'museum.region': 'Region',
    'museum.archive_preview': 'Digital Archive Preview',
    'museum.scan_count': 'SCAN_COUNT',
    'museum.status_open': 'Status: Open',
    'museum.access_fee': 'Access Fee',
    'museum.verified_archive': 'Ministry Verified Archive',
    'museum.certified': 'Ministry Certified Institution',
    'artifact.era': 'Chronological Era',
    'artifact.registry_entry': 'Registry Entry',
    'artifact.custodian': 'Current Custodian',
    'artifact.verification': 'Verification Status',
    'artifact.authentic': 'Authentic — National Registry Verified',
    'dashboard.census': 'National Heritage Census 2026',
    'dashboard.performance': 'Institutional Performance',
    'dashboard.report': 'National Heritage Institutional Performance Report',
    'dashboard.integrity': 'Data Integrity Verified',
    'dashboard.ministry': 'Ministry of Culture & Arts',
    'dashboard.reg_inst': 'Registered Institutions',
    'dashboard.visitors': 'Verified Annual Visitors',
    'dashboard.satisfaction': 'Public Satisfaction Index',
    'dashboard.wilayas': 'Administrative Wilayas',
    'dashboard.matrix': 'Visitor Distribution Matrix',
    'dashboard.traffic': 'Monthly Institutional Traffic',
    'dashboard.distribution': 'Visitor Distribution',
    'dashboard.metrics': 'Monthly Traffic Metrics',
    'dashboard.density': 'Regional Density',
    'dashboard.geo_dist': 'Geographic Distribution',
    'dashboard.heritage_density': 'Heritage Density',
    'dashboard.sector': 'Sector',
    'dashboard.units': 'Units',
    'dashboard.geospatial': 'Access National Geospatial Registry',
    'newsletter.title': 'Join the Registry',
    'newsletter.arabic_title': 'انضم إلى السجل الوطني',
    'newsletter.description': 'Receive exclusive updates on new archaeological discoveries and museum exhibitions across the Republic.',
    'newsletter.placeholder': 'Email address...',
    'atlas.geospatial': 'National Geospatial Registry',
    'atlas.lat': 'LAT',
    'atlas.lng': 'LNG',
    'atlas.alt': 'ALT',
    'atlas.status': 'SYSTEM_STATUS',
    'atlas.nominal': 'NOMINAL',
    'newsletter.subscribers_count': '10k+',
    'newsletter.subscribe': 'Subscribe',
    'newsletter.subscribers': 'Subscribers',
    'chronicles.title': 'The Heritage Chronicles',
    'chronicles.arabic_title': 'سجلات التراث الخالدة عبر العصور',
    'chronicles.tagline': 'Historical Timeline',
    'footer.tagline': 'The official digital repository of the Republic of Algeria\'s cultural and historical legacy. Preserved for eternity, accessible to all.',
    'footer.registry': 'Registry',
    'footer.archives': 'Archives',
    'footer.research': 'Research',
    'footer.digital_twins': 'Digital Twins',
    'footer.publications': 'Publications',
    'footer.educational': 'Educational',
    'footer.headquarters': 'Headquarters',
    'footer.location': 'Location',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2026 Republic of Algeria — National Heritage Portal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Access',
    'footer.republic': 'People\'s Democratic Republic of Algeria',
  },
  ar: {
    'nav.collections': 'المجموعات',
    'nav.exhibitions': 'المعارض',
    'nav.archives': 'الأرشيف',
    'nav.analytics': 'التحليلات',
    'nav.access': 'بوابة الدخول',
    'nav.logo_algerian': 'التراث',
    'nav.logo_heritage': 'الجزائري',
    'nav.tagline': 'البوابة الوطنية للمتاحف',
    'hero.portal_tagline': 'بوابة التراث الوطني — الجزائر',
    'hero.title': 'اكتشف قلب',
    'hero.subtitle': 'التراث الجزائري',
    'hero.description': 'استكشف التاريخ الغني والكنوز الثقافية للجزائر من خلال شبكة متاحفنا الوطنية.',
    'hero.search': 'ابحث عن المتاحف، الآثار، أو المناطق...',
    'hero.all_records': 'كل السجلات',
    'hero.archaeology': 'علم الآثار',
    'hero.fine_arts': 'الفنون الجميلة',
    'hero.history': 'التاريخ',
    'hero.search_btn': 'بحث',
    'hero.cta': 'استكشف السجل',
    'hero.institutions': 'مؤسسة',
    'hero.archived': 'سجل مؤرشف',
    'hero.years': 'سنة من التاريخ',
    'hero.monument': 'معلم وطني',
    'hero.algiers': 'الجزائر العاصمة',
    'hero.tagline': 'حماية روح الأمة',
    'mission.title': 'حراس الشعلة الأبدية',
    'mission.arabic_title': 'حراس الشعلة الأبدية للتراث',
    'mission.tagline': 'مهمتنا المقدسة',
    'mission.description': 'نحن نؤمن بأن التراث ليس مجرد مجموعة من الأشياء، بل هو حوار حي بين أسلافنا والمستقبل. مهمتنا هي ضمان أن كل جزائري، أينما كان، يمكنه لمس روح تاريخه.',
    'mission.preservation': 'الحفاظ',
    'mission.accessibility': 'الوصول',
    'mission.archives': 'أرشيفات متطورة',
    'mission.digital': 'وصول رقمي عالمي',
    'mission.charter': 'اقرأ ميثاقنا الكامل',
    'mission.education': 'التعليم',
    'mission.education_desc': 'تمكين الجيل القادم من الحقيقة التاريخية.',
    'mission.research': 'البحث',
    'mission.research_desc': 'توفير منصة عالمية للدراسات الأثرية.',
    'mission.unesco': 'شريك اليونسكو',
    'mission.soul': 'الحفاظ على روح الجزائر',
    'mission.soul_desc': 'مهمتنا تتجاوز مجرد الأرشفة. نحن حراس رواية عمرها 3000 عام، نضمن أن أصداء أسلافنا تتردد عبر العصر الرقمي.',
    'spotlight.title': 'روح المقاومة',
    'spotlight.arabic_title': 'روح المقاومة والتحرر',
    'spotlight.tagline': 'تسليط الضوء الوطني',
    'spotlight.description': 'رحلة عبر أروقة الزمن، حيث تحكي كل قطعة أثرية قصة شجاعة وتضحية وسعي لا يلين نحو الحرية.',
    'spotlight.cta': 'استكشف الثورة',
    'spotlight.featured': 'موقع مميز',
    'spotlight.maqam': 'مقام الشهيد',
    'spotlight.verified': 'أرشيف معتمد',
    'spotlight.mujahid_desc': 'يحفظ المتحف الوطني للمجاهد أكثر من 50,000 قطعة أثرية من ثورة التحرير الجزائرية.',
    'spotlight.year': '١٩٦٢',
    'treasury.title': 'الخزانة الوطنية',
    'treasury.arabic_title': 'الخزانة الوطنية للتراث الجزائري',
    'treasury.tagline': 'روائع مختارة',
    'treasury.description': 'مجموعة دقيقة من أهم الآثار الجزائرية، تمتد من عصور ما قبل التاريخ إلى العصر الحديث للاستقلال.',
    'treasury.examine': 'فحص سجل الأرشيف',
    'treasury.registry_count': 'عدد السجلات',
    'treasury.last_updated': 'آخر تحديث',
    'treasury.month': 'مارس 2026',
    'inventory.title': 'الأرشيف المؤسسي',
    'inventory.arabic_title': 'سجل المؤسسات التراثية المعتمدة',
    'inventory.tagline': 'السجل الوطني',
    'inventory.active': 'سجلات السجل النشطة',
    'inventory.no_results': 'لا توجد سجلات مطابقة',
    'inventory.reset': 'إعادة ضبط مرشحات السجل',
    'inventory.active_records': 'سجلات السجل النشطة',
    'inventory.no_matching': 'لا توجد سجلات مطابقة',
    'inventory.no_matching_desc': 'لم يتمكن السجل من العثور على أي مؤسسات تطابق معايير البحث الحالية.',
    'atlas.title': 'أطلس التراث',
    'atlas.arabic_title': 'أطلس التراث الوطني',
    'atlas.tagline': 'الاكتشاف الجغرافي',
    'atlas.cta': 'افتح الأطلس التفاعلي',
    'eras.chronicles': 'سجلات الزمن',
    'eras.title': 'عصور الحضارة',
    'eras.view_archives': 'عرض الأرشيف',
    'eras.verified': 'عصر معتمد',
    'eras.period': 'الفترة التاريخية',
    'museum.access_coords': 'الوصول إلى الإحداثيات',
    'museum.gps': 'نظام تحديد المواقع',
    'museum.algeria': 'الجزائر',
    'museum.region': 'المنطقة',
    'museum.archive_preview': 'معاينة الأرشيف الرقمي',
    'museum.scan_count': 'عدد المسحات',
    'museum.status_open': 'الحالة: مفتوح',
    'museum.access_fee': 'رسوم الدخول',
    'museum.verified_archive': 'أرشيف معتمد وزارياً',
    'museum.certified': 'مؤسسة معتمدة وزارياً',
    'artifact.era': 'العصر الزمني',
    'artifact.registry_entry': 'إدخال السجل',
    'artifact.custodian': 'الحارس الحالي',
    'artifact.verification': 'حالة التحقق',
    'artifact.authentic': 'أصيل — معتمد من السجل الوطني',
    'dashboard.census': 'الإحصاء الوطني للتراث 2026',
    'dashboard.performance': 'أداء المؤسسات',
    'dashboard.report': 'تقرير أداء المؤسسات التراثية الوطنية',
    'dashboard.integrity': 'تم التحقق من سلامة البيانات',
    'dashboard.ministry': 'وزارة الثقافة والفنون',
    'dashboard.reg_inst': 'المؤسسات المسجلة',
    'dashboard.visitors': 'إجمالي الزوار السنوي',
    'dashboard.satisfaction': 'مؤشر رضا الجمهور',
    'dashboard.wilayas': 'الولايات الإدارية',
    'dashboard.matrix': 'مصفوفة توزيع الزوار',
    'dashboard.traffic': 'حركة المرور المؤسسية الشهرية',
    'dashboard.distribution': 'توزيع الزوار',
    'dashboard.metrics': 'مقاييس الحركة الشهرية',
    'dashboard.density': 'الكثافة الإقليمية',
    'dashboard.geo_dist': 'التوزيع الجغرافي',
    'dashboard.heritage_density': 'كثافة التراث',
    'dashboard.sector': 'قطاع',
    'dashboard.units': 'وحدات',
    'dashboard.geospatial': 'الوصول إلى السجل الجغرافي الوطني',
    'newsletter.title': 'انضم إلى السجل',
    'newsletter.arabic_title': 'انضم إلى السجل الوطني',
    'newsletter.description': 'احصل على تحديثات حصرية حول الاكتشافات الأثرية الجديدة ومعارض المتاحف في جميع أنحاء الجمهورية.',
    'newsletter.placeholder': 'عنوان البريد الإلكتروني...',
    'atlas.geospatial': 'السجل الجغرافي الوطني',
    'atlas.lat': 'خط العرض',
    'atlas.lng': 'خط الطول',
    'atlas.alt': 'الارتفاع',
    'atlas.status': 'حالة النظام',
    'atlas.nominal': 'طبيعي',
    'newsletter.subscribers_count': '+10 آلاف',
    'newsletter.subscribe': 'اشترك',
    'newsletter.subscribers': 'مشترك',
    'chronicles.title': 'سجلات التراث',
    'chronicles.arabic_title': 'سجلات التراث الخالدة عبر العصور',
    'chronicles.tagline': 'الخط الزمني التاريخي',
    'footer.tagline': 'المستودع الرقمي الرسمي للإرث الثقافي والتاريخي للجمهورية الجزائرية. محفوظ للأبد، متاح للجميع.',
    'footer.registry': 'السجل',
    'footer.archives': 'الأرشيف',
    'footer.research': 'الأبحاث',
    'footer.digital_twins': 'التوائم الرقمية',
    'footer.publications': 'المنشورات',
    'footer.educational': 'التعليمية',
    'footer.headquarters': 'المقر الرئيسي',
    'footer.location': 'الموقع',
    'footer.contact': 'اتصل بنا',
    'footer.copyright': '© 2026 الجمهورية الجزائرية — بوابة التراث الوطني',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الوصول',
    'footer.republic': 'الجمهورية الجزائرية الديمقراطية الشعبية',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
